---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    channel: {{ .Values.secret.channel }}
    dapnet: {{ .Values.secret.dapnet }}
    token: {{ .Values.secret.token }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Release.Name }}-secrets
      namespace: {{ .Release.Namespace }}
    type: Opaque
